#ifndef RXFCONSTANTS_H 
#define RXFCONSTANTS_H 

/* $Id: RxfConstants.h 30652 2014-11-14 10:09:59Z eroemer $
 * $URL: https://svn.willert.de/V6/trunk/Component/Modelling/EA/Source/C/RxfConstants.h $
 * 
 * This RxfConstants.h is used initially to create RXF libraries with the CreateRXFLib IDE project or animation libraries.
 * This file is normally generated by Rhapsody, based on your actual properties, so you may need to recreate the libraries.  
 * Default values are configured to support libraries in evaluation versions.
 */

 
#define WST_RXF_V6
#define WST_PORTS_DISABLED
#define WST_CFG_HIGHWATERMARKS


#endif /* RXFCONSTANTS_H */ 
